### ISSUE TITLE
我的配置应该和你的一样吧，可以使用？

### ISSUE THREAD

**Issue by hx2nn** [Butanediol/MSI-B450m-Mortar-EFI#2]
![image](https://user-images.githubusercontent.com/57549367/145126274-1134d9bc-0e14-4122-9923-d20f13ea293b.png)
显卡已经更换成amd的免驱显卡，现在已经安装并且使用中，不过版本很久，准备用您的EFI，试试mac12

**Comment by Butanediol** [comment]
主板不一样不做保证，不过我近期可能再更新一下 EFI 到 0.7.5 或者 0.7.6。
